name: JohnRodriguez
favicon: null
layout_spectrum: 0.6099538577254862
typography_spectrum: 0.6186669217422605
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8043379706796259
  lightness: 0.8142359515186399
  saturation: 0.5438546533696353
  rhythmicContrast: 0.06677943398244679
purpose: []
