name: JohnRodriguez
favicon: null
layout_spectrum: 0.24566
typography_spectrum: 0.94236
title: 'Student Affairs Professional Challenging Educational Norms & Best Practices'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#292929'
    - '#6ea6bf'
    - '#00aa47'
    - '#00cbef'
  brandStrength: 0.9375
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
