analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.09538
title: John Orlando Rodriguez
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0
  brandStrength: 0.5
  rhythmicContrast: 0
  brandColors:
    - '#ffffff'
    - '#292929'
    - '#6ea6bf'
    - '#00aa47'
    - '#00cbef'
  lightness: 1
purpose: []
favicon: null
name: John Rodriguez
typography_spectrum: 0.61658
