name: JohnRodriguez
favicon: null
layout_spectrum: 0.09538
typography_spectrum: 0.61658
title: 'Student Affairs Professional Challenging Educational Norms & Best Practices'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#35f6da'
    - '#191612'
    - '#1f7d6e'
    - '#2ecfb7'
    - '#6b6557'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
